AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend APIs

Parameters: # Can be accessed using process.env.apiRootUrl
  apiRootUrl:
    Type: String
  apiRootUrlRoute53:
    Type: String
  apiRootCertificateArn:
    Type: String

Resources:
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      DisableExecuteApiEndpoint: true
      StageName: Prod
      Name: Backend API
      AlwaysDeploy: true
      Domain: 
        DomainName: !Ref apiRootUrl
        CertificateArn: !Ref apiRootCertificateArn
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref apiRootUrlRoute53
      Auth:
        Authorizers:
          OpenToAll:
            FunctionArn: !GetAtt OpenToAllAuthorizer.Arn
            Identity:
              ReauthorizeEvery: 300 # seconds
      
  Info: 
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers
      Handler: info-handler.handle
      Runtime: nodejs18.x
      Events:
        GetInfo:
          Type: Api
          Properties:
            RestApiId: !Ref RestAPI
            Path: /info/v1
            Method: get
            # No Authorizer will be required for this API as
            # it would still require the Authorization header 
            # to be provided.
            # Auth:
            #   Authorizer: OpenToAll

  OpenToAllAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/authorizers
      Handler: open-to-all.authorize
      Runtime: nodejs18.x

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod
  ApiId:
    Description: API Gateway ID
    Value:
      Fn::Sub: ${RestAPI}
